query infiniteScrollPosts($pageNum: Int!, $pageSize: Int!) {
  infiniteScrollPosts(pageNum: $pageNum, pageSize: $pageSize) {
    hasMore
    posts {
      _id
      title
      imageUrl
      categories
      description
      likes
      createdDate
      messages {
        _id
      }
      createdBy {
        _id
        username
        avatar
      }
    }
  }
}
