mutation updateUserPost(
  $postId: ID!
  $userId: ID!
  $title: String!
  $imageUrl: String!
  $categories: [String]!
  $description: String!
) {
  updateUserPost(
    postId: $postId
    userId: $userId
    title: $title
    imageUrl: $imageUrl
    categories: $categories
    description: $description
  ) {
    _id
    title
    imageUrl
    description
    categories
    createdDate
    likes
    createdBy {
      _id
      avatar
    }
  }
}
